version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false 
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.3
    container_name: logstash    

    depends_on:
      - elasticsearch
    ports:
      - 5044:5044
      - 5000:5000/tcp
      - 5000:5000/udp
      - 9600:9600
    expose:
      - 5044
   
    links:
    - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.3
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

